4:
  # 91.27
  - title: S. Maria in sabbato
    type: feria
    occurence: sabbato
3:
  # 91.26
  - type: vigilia
    occurence: saints
  # 91.25
  - type: feria
    occurence: { start: advent, end: 12-16 }
  # 91.24
  - type: festum
    occurence: saints
  # 91.23
  - type: festum
    occurence: propers
  # 91.22
  - type: feria
    priviliged: true
    occurence:
      start: { date: easter, difference: -46 }
      end: easter
2:
  # 91.21
  - type: vigilia
    occurence: saints
  - title: In vigilia Ascensionis
    type: vigilia
    occurence: { date: easter, difference: 38 }
  # 91.20
  - type: festum
    occurence: indults
  # 91.19
  - type: festum
    occurence: propers
  # 91.18
  - type: feria
    occurence: { start: 12-17, end: 12-23 }
  - type: quartertemper
    occurence: { type: ember, start: 12-15 }
  - type: quartertemper
    occurence:
      type: ember
      start: { date: easter, difference: -39 }
  - type: quartertemper
    occurence: { type: ember, start: 09-18 }
  # 91.17
  - type: octava
    occurence: { start: 12-26, end: 12-31 }
  - title: Dominica infra octavam Nativitatis Domini
    type: dominica
    occurence: { start: 12-26, end: 12-31 }
  # 91.16
  - type: festum
    occurence: saints
  # 91.15
  - title: Dominica $count post Epiphaniam
    type: dominica
    occurence:
      start: 01-07
      end: { date: easter, difference: -70 }
  - title: Dominica in Septuagesima
    type: dominica
    occurence: { date: easter, difference: -63 }
  - title: Dominica in Sexagesima
    type: dominica
    occurence: { date: easter, difference: -56 }
  - title: Dominica in Quinquagesima
    type: dominica
    occurence: { date: easter, difference: -49 }
  - title: Dominica $count post Pascha
    type: dominica
    occurence:
      start: { date: easter, difference: 7 }
      end: { date: easter, difference: 35 }
  - title: Dominica II post Pascha
    type: dominica
    occurence: { date: easter, difference: 14 }
  - title: Dominica post Ascensionem
    type: dominica
    occurence: { date: easter, difference: 42 }
  - title: Dominica $count post Pentecosten
    type: dominica
    occurence:
      start: { date: easter, difference: 56 }
      end: { date: easter, difference: 245 }
  # 91.14
  - title: Ssm̃i Nominis Jesu
    type: festum
    occurence:
      type: dominica
      start: 01-02
      end: 01-05
      default: 01-02
  - title: Dominica I post Epiphaniam, Sanctæ Familiæ Jesu, Mariæ, Joseph
    type: festum
    occurence:
      type: dominica
      start: 01-07
      end: 01-13
  - title: Dominica II post Pentecosten
    type: festum
    occurence: { date: easter, difference: 63 }
  - type: domini
    occurence: saints
1:
  # 91.13
  - type: festum
    occurence: indults
  # 91.12
  - type: festum
    occurence: propers
  # 91.11
  - type: festum
    occurence: saints
  # 91.10
  - type: octava
    occurence:
      start: { date: easter, difference: 2 }
      end: { date: easter, difference: 7 }
  - title: Feria II infra octavam Paschæ
    type: octava
    occurence: { date: easter, difference: 1 }
  - type: octava
    occurence:
      start: { date: easter, difference: 51 }
      end: { date: easter, difference: 56 }
  - type: quartertemper
    occurence:
      type: ember
      start: { date: easter, difference: 52 }
  - title: Feria II infra octavam Pentecostes
    type: octava
    occurence: { date: easter, difference: 50 }
  # 91.9
  - title: Sabbato in vigilia Pentecostes
    type: vigilia
    occurence: { date: easter, difference: 48 }
  # 91.8
  - type: feria
    occurence:
      type: "!dominica"
      start: 11-02
      end: 11-03
  # 91.7
  - title: Feria quarta cinerum
    type: feria
    occurence: { date: easter, difference: -46 }
  - type: feria
    occurence:
      start: { date: easter, difference: -6 }
      end: { date: easter, difference: -4 }
    # 91.6
  - title: Dominica $count Adventus
    type: dominica
    occurence: { start: 11-27, end: 12-24 }
  - title: Dominica $count in Quadragesima
    type: dominica
    occurence:
      start: { date: easter, difference: -42 }
      end: { date: easter, difference: -21 }
  - title: Dominica I Passionis
    type: dominica
    occurence: { date: easter, difference: -14 }
  - title: Dominica II Passionis seu in Palmis
    type: dominica
    occurence: { date: easter, difference: -7 }
  - title: Dominica in albis
    type: dominica
    occurence: { date: easter, difference: 7 }
  # 91.5
  - type: vigilia
    occurence: { type: saints, date: 12-24 }
  - type: octava
    occurence: { type: saints, date: 01-01 }
  # 91.4
  - type: festum
    occurence: { type: saints, date: 12-08 }
  - type: festum
    occurence: { type: saints, date: 08-15 }
  # 91.3
  - type: festum
    occurence: { type: saints, date: 01-06 }
  - title: In Ascensione Domini
    type: festum
    occurence: { date: easter, difference: 39 }
  - title: In festo Sanctissimæ Trinitatis
    type: dominica
    occurence: { date: easter, difference: 56 }
  - title: In festo Ssm̃i Corporis Christi
    type: festum
    occurence: { date: easter, difference: 60 }
  - title: In festo Sacratissimi Cordis Jesu
    type: festum
    occurence: { date: easter, difference: 68 }
  - title: D.N. Jesu Christi Regis
    type: festum
    occurence:
      type: dominica
      start: 10-25
      end: 10-31
  # 91.2
  - title: Feria V in Cena Domini
    type: feria
    occurence: { date: easter, difference: -3 }
  - title: Feria VI in Passione et Morte Domini
    type: feria
    occurence: { date: easter, difference: -2 }
  - title: Sabbato sancto
    type: feria
    occurence: { date: easter, difference: -1 }
  # 91.1
  - type: festum
    occurence: { type: saints, date: 12-25 }
  - title: Dominica Resurrectionis
    type: festum
    occurence: easter
  - title: Dominica Pentecostes
    type: festum
    occurence: { date: easter, difference: 49 }
